import type { Metadata } from "next";
import localFont from 'next/font/local';
import '../styles/theme';
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: '../../public/fonts/aglet-sans-bold.otf',
      weight: '700',
      style: 'bold'
    },
    {
      path: '../../public/fonts/aglet-sans-semibold.otf',
      weight: '600',
      style: 'semibold'
    },
    {
      path: '../../public/fonts/aglet-sans-normal.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../../public/fonts/aglet-sans-regular.otf',
      weight: '400',
      style: 'regular'
    },
  ],
  variable: '--font-aglet-sans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.variable}`}>{children}</body>
    </html>
  );
}
