import type { Metadata } from "next";
import localFont from 'next/font/local';
import '../styles/theme';
import "./globals.css";

const myFont = localFont({ src: '../../public/fonts/aglet-sans-bold.otf' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
